//@ui5-bundle com/snet/proj/zprojmassupdate/Component-preload.js
sap.ui.require.preload({
	"com/snet/proj/zprojmassupdate/Component.js":function(){
sap.ui.define(["sap/ui/core/UIComponent","sap/ui/Device","com/snet/proj/zprojmassupdate/model/models"],function(e,t,i){"use strict";return e.extend("com.snet.proj.zprojmassupdate.Component",{metadata:{manifest:"json"},init:function(){e.prototype.init.apply(this,arguments);this.getRouter().initialize();this.setModel(i.createDeviceModel(),"device")}})});
},
	"com/snet/proj/zprojmassupdate/controller/App.controller.js":function(){
sap.ui.define(["sap/ui/core/mvc/Controller"],function(n){"use strict";return n.extend("com.snet.proj.zprojmassupdate.controller.App",{onInit:function(){}})});
},
	"com/snet/proj/zprojmassupdate/controller/View1.controller.js":function(){
sap.ui.define(["sap/ui/core/mvc/Controller","sap/m/MessageToast"],function(e,t){"use strict";return e.extend("com.snet.proj.zprojmassupdate.controller.View1",{onInit:function(){},onUpdate:function(e){var a=this.getView().getModel();var i={};i.ProjectDefinition=this.getView().byId("idProjectCode").getValue();i.PlannedFinishDate=this.getView().byId("idDueDate").getDateValue();if(i.ProjectDefinition.length===0||i.ProjectDefinition===""){t.show("Please enter the Project Code");return}var n=sap.ui.core.format.DateFormat.getDateInstance({pattern:"MM/dd/yyyy"});i.PlannedFinishDate=n.format(i.PlannedFinishDate);if(i.PlannedFinishDate===""||i.PlannedFinishDate===null){t.show("Please enter the valid date!!");this.getView().byId("idDueDate").setDateValue();return}a.create("/ProjectSet",i,{method:"POST",success:function(e){this.getView().byId("idDueDate").setDateValue();t.show("Due Date has been successfully updated for the project ' "+e.ProjectDefinition+"'")}.bind(this),error:function(e){this.getView().byId("idDueDate").setDateValue();t.show(JSON.parse(e.responseText).error.message.value)}.bind(this)})},onChangeOfProject:function(e){var t=e.getSource();var a=t.getValue();var i=/^[a-zA-Z0-9.]*$/;if(!i.test(a)){var n=a.slice(0,-1);t.setValue(n)}}})});
},
	"com/snet/proj/zprojmassupdate/i18n/i18n.properties":'# This is the resource bundle for com.snet.proj.zprojmassupdate\n\n#Texts for manifest.json\n\n#XTIT: Application name\nappTitle=Update Project Customer Due Date\n\n#YDES: Application description\nappDescription=Update Project customer Due Date\n#XTIT: Main view title\ntitle=Update Project Customer Due Date\nprojectCode = Project Code\ncustDueDate = Customer Due Date\nbtnUpdate = Update',
	"com/snet/proj/zprojmassupdate/manifest.json":'{"_version":"1.58.0","sap.app":{"id":"com.snet.proj.zprojmassupdate","type":"application","i18n":"i18n/i18n.properties","applicationVersion":{"version":"0.0.1"},"title":"{{appTitle}}","description":"{{appDescription}}","resources":"resources.json","sourceTemplate":{"id":"@sap/generator-fiori:basic","version":"1.11.3","toolsId":"f4ceca8e-4ea9-45da-b971-ed97cf45ccf9"},"dataSources":{"PROJECT_UPDATE":{"uri":"/sap/opu/odata/sap/PROJECT_UPDATE","type":"OData","settings":{"annotations":[],"localUri":"localService/metadata.xml","odataVersion":"2.0"}}}},"sap.ui":{"technology":"UI5","icons":{"icon":"","favIcon":"","phone":"","phone@2":"","tablet":"","tablet@2":""},"deviceTypes":{"desktop":true,"tablet":true,"phone":true}},"sap.ui5":{"flexEnabled":true,"dependencies":{"minUI5Version":"1.120.0","libs":{"sap.m":{},"sap.ui.core":{},"sap.f":{},"sap.suite.ui.generic.template":{},"sap.ui.comp":{},"sap.ui.generic.app":{},"sap.ui.table":{},"sap.ushell":{}}},"contentDensities":{"compact":true,"cozy":true},"models":{"i18n":{"type":"sap.ui.model.resource.ResourceModel","settings":{"bundleName":"com.snet.proj.zprojmassupdate.i18n.i18n"}},"":{"preload":true,"dataSource":"PROJECT_UPDATE","settings":{"defaultBindingMode":"TwoWay","defaultCountMode":"Inline","refreshAfterChange":false,"metadataUrlParams":{"sap-value-list":"none"}}}},"resources":{"css":[{"uri":"css/style.css"}]},"routing":{"config":{"routerClass":"sap.m.routing.Router","viewType":"XML","async":true,"viewPath":"com.snet.proj.zprojmassupdate.view","controlAggregation":"pages","controlId":"app","clearControlAggregation":false},"routes":[{"name":"RouteView1","pattern":":?query:","target":["TargetView1"]}],"targets":{"TargetView1":{"viewType":"XML","transition":"slide","clearControlAggregation":false,"viewId":"View1","viewName":"View1"}}},"rootView":{"viewName":"com.snet.proj.zprojmassupdate.view.App","type":"XML","async":true,"id":"App"}}}',
	"com/snet/proj/zprojmassupdate/model/models.js":function(){
sap.ui.define(["sap/ui/model/json/JSONModel","sap/ui/Device"],function(e,n){"use strict";return{createDeviceModel:function(){var i=new e(n);i.setDefaultBindingMode("OneWay");return i}}});
},
	"com/snet/proj/zprojmassupdate/view/App.view.xml":'<mvc:View controllerName="com.snet.proj.zprojmassupdate.controller.App"\n    xmlns:html="http://www.w3.org/1999/xhtml"\n    xmlns:mvc="sap.ui.core.mvc" displayBlock="true"\n    xmlns="sap.m"><Shell id="shell"><App id="app"></App></Shell></mvc:View>\n',
	"com/snet/proj/zprojmassupdate/view/View1.view.xml":'<mvc:View controllerName="com.snet.proj.zprojmassupdate.controller.View1"\n     xmlns:mvc="sap.ui.core.mvc" displayBlock="true"\n    xmlns="sap.m"\t\n\txmlns:l="sap.ui.layout"\n\txmlns:f="sap.ui.layout.form"\n\txmlns:core="sap.ui.core"\n    ><Page id="page" title="{i18n>title}" icon=""><content ><VBox class="sapUiSmallMargin"><f:SimpleForm id="SimpleFormChangeColumn_twoGroups234"\n\t\t\teditable="true"\n\t\t\tlayout="ColumnLayout"\n\t\t\ttitle=""\n\t\t\tcolumnsM="2"\n\t\t\tcolumnsL="3"\n\t\t\tcolumnsXL="4"\n\t\t\t><f:content><core:Title text="" /><Label text="{i18n>projectCode}" /><Input id="idProjectCode" value="" liveChange="onChangeOfProject" maxLength="24"/><core:Title text="" /><Label text="{i18n>custDueDate}" labelFor="DP2"/><DatePicker id = "idDueDate" displayFormat="MM/dd/yyyy" valueFormat="yyyyMMdd" change="onDateChange"/></f:content></f:SimpleForm></VBox></content><footer><OverflowToolbar><ToolbarSpacer/><Button text="{i18n>btnUpdate}" press="onUpdate" width="13rem" type="Emphasized" enabled="true"></Button></OverflowToolbar></footer></Page></mvc:View>\n'
});
//# sourceMappingURL=Component-preload.js.map
